/*
 * Copyright (c) 2026 EdgeImpulse Inc.
 *
 * Generated by Edge Impulse and licensed under the applicable Edge Impulse
 * Terms of Service. Community and Professional Terms of Service
 * (https://edgeimpulse.com/legal/terms-of-service) or Enterprise Terms of
 * Service (https://edgeimpulse.com/legal/enterprise-terms-of-service),
 * according to your product plan subscription (the “License”).
 *
 * This software, documentation and other associated files (collectively referred
 * to as the “Software”) is a single SDK variation generated by the Edge Impulse
 * platform and requires an active paid Edge Impulse subscription to use this
 * Software for any purpose.
 *
 * You may NOT use this Software unless you have an active Edge Impulse subscription
 * that meets the eligibility requirements for the applicable License, subject to
 * your full and continued compliance with the terms and conditions of the License,
 * including without limitation any usage restrictions under the applicable License.
 *
 * If you do not have an active Edge Impulse product plan subscription, or if use
 * of this Software exceeds the usage limitations of your Edge Impulse product plan
 * subscription, you are not permitted to use this Software and must immediately
 * delete and erase all copies of this Software within your control or possession.
 * Edge Impulse reserves all rights and remedies available to enforce its rights.
 *
 * Unless required by applicable law or agreed to in writing, the Software is
 * distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing
 * permissions, disclaimers and limitations under the License.
 */

#ifndef _EI_CLASSIFIER_MODEL_VARIABLES_H_
#define _EI_CLASSIFIER_MODEL_VARIABLES_H_

/**
 * @file
 *  Auto-generated complete impulse definitions. The ei_impulse_handle_t should
 *  be passed to ei_run_classifier() function to use this specific impulse.
 *  This file should only be included in ei_run_classifier.h file.
 */

#include <stdint.h>
#include "model_metadata.h"
#include "tflite-model/tflite_learn_1071949_3.h"
#include "edge-impulse-sdk/classifier/ei_model_types.h"
#include "edge-impulse-sdk/classifier/inferencing_engines/engines.h"
#include "edge-impulse-sdk/classifier/postprocessing/ei_postprocessing_common.h"

const char* ei_classifier_inferencing_categories_1071949_1[] = { "noisy", "quiet_room_white_noise", "speech" };

EI_CLASSIFIER_DSP_AXES_INDEX_TYPE ei_dsp_config_1071949_2_axes[] = { 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56 };
const uint32_t ei_dsp_config_1071949_2_axes_size = 57;
ei_dsp_config_raw_t ei_dsp_config_1071949_2 = {
    2, // uint32_t blockId
    1, // int implementationVersion
    57, // int length of axes
    1.0f // float scale-axes
};

const float ei_dn_standard_scaler_mean_1071949_2[57] = { -86.43143481563254, 0.6175174443654105, 1.556782609001162, 423.7097106049026, 180.38418707179562, 444.6956520743992, 0.4274621067703634, 0.14385687813414755, 0.3690102018199969, 0.36200159428200285, 0.14382191692537444, 0.36876000726352565, 0.23022160561044436, 0.09376011213044758, 0.2403559808227895, 0.21685840646569857, 0.0694769242355501, 0.17820847340396062, 0.0929979614229594, 0.031064564438203827, 0.07979524152686343, 0.09792042103942465, 0.029079755004225435, 0.07491943666819428, 65.17260883718298, 22.662857125692323, 52.20724566915761, 284.9522942584494, 73.89748777306598, 183.2067606313217, 749.891666430782, 192.5999548446729, 481.6711106710388, 2781.1916676102055, 579.0930251227485, 1452.8636696488386, 7307.9701445501205, 1589.2451619834715, 3994.522315278721, 0.4380194766221991, 0.09843568248935224, 0.2511768726605004, 250.02490349368773, 230.00165499258733, 556.4512078842679, 0.46922223583799627, 0.1383933141746599, 0.3551908002491447, 0.3816421703583952, 0.11609636673226881, 0.29874705798060136, 0.14913559111132138, 0.04833918382989576, 0.12447090720676858, 0.0013005617082541907, 0.0005512621151742437, 0.0013750264616185408 };
const float ei_dn_standard_scaler_scale_1071949_2[57] = { 2.510805795212041, 1.8242085070173757, 0.760157555485524, 0.005400545661044183, 0.003715658986825477, 0.0015649164041732033, 11.339922622265941, 18.501658051358923, 7.207861127147051, 11.392198571871019, 18.335875704436468, 7.166292197121925, 17.12694413877398, 20.819306498076557, 8.17389387031497, 21.067042774439283, 27.35234678059122, 10.710786217964028, 44.38600127886061, 43.844378057849056, 17.497224784322526, 54.81140792114629, 75.64489781618082, 29.2686860026576, 0.0631481046879195, 0.06118248520173002, 0.02632431262659808, 0.022221969857412083, 0.03547939496807788, 0.014293116533991112, 0.007460302888796631, 0.008022563667860886, 0.0032243728070535135, 0.0026144426567218017, 0.0032805742678570183, 0.0013285364323044082, 0.0010256071455979686, 0.0015598367700646596, 0.0006317900006793484, 16.121698581597848, 22.13342821075812, 8.70594926817475, 0.00473343471377689, 0.003555215270603501, 0.001478154869911847, 11.777923572600331, 18.55748361752932, 7.172641138139287, 13.882318678871036, 19.43892929065604, 7.524787994704628, 30.678462051157066, 34.28474275363755, 13.524989571713713, 1291.8870793774147, 794.803368202191, 340.4186511934943 };
const float ei_dn_standard_scaler_var_1071949_2[57] = { 0.15862577437787573, 0.30050454619477507, 1.7305843303285044, 34286.623249147626, 72431.63730319055, 408336.0411101098, 0.007776421953833227, 0.002921317093642541, 0.01924806953327553, 0.007705217588727902, 0.0029743816108954834, 0.019472018608718493, 0.003409103900108701, 0.0023071056476707493, 0.014967249935195763, 0.0022531642191502567, 0.0013366287926807991, 0.008716804340481192, 0.000507584039123481, 0.0005202021852222431, 0.0032663420178559127, 0.0003328572987658356, 0.0001747594699811211, 0.0011673297367560866, 250.77218236350402, 267.14421398701865, 1443.0650893291702, 2025.0459942701418, 794.4152813534363, 4894.926001717066, 17967.476254312503, 15537.23216502258, 96185.47638829878, 146299.13503658617, 92918.08527400484, 566569.3322589213, 950687.8071831173, 410999.8775466951, 2505269.803977272, 0.003847498026474742, 0.0020412802205383236, 0.013193734360037736, 44632.08927356483, 79116.70552652764, 457678.0906021649, 0.007208792690522775, 0.002903767420959756, 0.019437562128741204, 0.0051889081179383265, 0.002646398976865634, 0.017660844349244344, 0.0010625095244009314, 0.0008507426576485637, 0.005466711085871046, 5.99171145273751e-7, 0.0000015829988604480637, 0.000008629255077537614 };
ei_data_normalization_standard_scaler_config_t ei_data_normalization_standard_scaler_config_1071949_2 = {
    .mean_data = (float *)ei_dn_standard_scaler_mean_1071949_2,
    .mean_data_len = 57,
    .scale_data = (float *)ei_dn_standard_scaler_scale_1071949_2,
    .scale_data_len = 57,
    .var_data = (float *)ei_dn_standard_scaler_var_1071949_2,
    .var_data_len = 57
};
ei_data_normalization_t ei_data_normalization_config_1071949_2 = {
    (void *) &ei_data_normalization_standard_scaler_config_1071949_2, // config
    DATA_NORMALIZATION_METHOD_STANDARD_SCALER, // method
    nullptr, // context
    nullptr, // init func
    nullptr, // deinit func
    &data_normalization_standard_scaler // exec func
};

const uint8_t ei_dsp_blocks_1071949_1_size = 1;
ei_model_dsp_t ei_dsp_blocks_1071949_1[ei_dsp_blocks_1071949_1_size] = {
    { // DSP block 2
        2,
        57, // output size
        &extract_raw_features, // DSP function pointer
        (void*)&ei_dsp_config_1071949_2, // pointer to config struct
        ei_dsp_config_1071949_2_axes, // array of offsets into the input stream, one for each axis
        ei_dsp_config_1071949_2_axes_size, // number of axes
        1, // version
        nullptr, // factory function
        &ei_data_normalization_config_1071949_2, // data normalization config
    }
};
const ei_config_tflite_graph_t ei_config_graph_1071949_3 = {
    .implementation_version = 1,
    .model = tflite_learn_1071949_3,
    .model_size = tflite_learn_1071949_3_len,
    .arena_size = tflite_learn_1071949_3_arena_size
};

const uint8_t ei_output_tensors_indices_1071949_3[1] = { 0 };
const uint8_t ei_output_tensors_size_1071949_3 = 1;
ei_learning_block_config_tflite_graph_t ei_learning_block_config_1071949_3 = {
    .implementation_version = 1,
    .block_id = 3,
    .output_tensors_indices = ei_output_tensors_indices_1071949_3,
    .output_tensors_size = ei_output_tensors_size_1071949_3,
    .quantized = 0,
    .compiled = 0,
    .graph_config = (void*)&ei_config_graph_1071949_3,
    .dequantize_output = 0,
};

const uint8_t ei_learning_blocks_1071949_1_size = 1;
const uint32_t ei_learning_block_1071949_3_inputs[1] = { 2 };
const uint8_t ei_learning_block_1071949_3_inputs_size = 1;
const ei_learning_block_t ei_learning_blocks_1071949_1[ei_learning_blocks_1071949_1_size] = {
    {
        3,
        &run_nn_inference,
        (void*)&ei_learning_block_config_1071949_3,
        EI_CLASSIFIER_IMAGE_SCALING_NONE,
        ei_learning_block_1071949_3_inputs,
        ei_learning_block_1071949_3_inputs_size,
    },
};

const size_t ei_postprocessing_blocks_1071949_1_size = 1;
const ei_postprocessing_block_t ei_postprocessing_blocks_1071949_1[ei_postprocessing_blocks_1071949_1_size] = {
    {
        .block_id = 3,
        .type = EI_CLASSIFIER_MODE_CLASSIFICATION,
        .init_fn = NULL,
        .deinit_fn = NULL,
        .postprocess_fn = &process_classification_f32,
        .display_fn = NULL,
        .config = NULL,
        .input_block_id = 3
    },
};

const uint8_t freeform_outputs_1071949_1_size = 0;

uint32_t *freeform_outputs_1071949_1 = nullptr;

const ei_impulse_t impulse_1071949_1 = {
    .project_id = 1071949,
    .project_owner = "dtoma3349",
    .project_name = "SDACS_V3",
    .impulse_id = 1,
    .impulse_name = "Impulse #1",
    .deploy_version = 1,

    .nn_input_frame_size = 57,
    .raw_sample_count = 1,
    .raw_samples_per_frame = 57,
    .dsp_input_frame_size = 1 * 57,
    .input_width = 0,
    .input_height = 0,
    .input_frames = 0,
    .interval_ms = 1,
    .frequency = 0,

    .dsp_blocks_size = ei_dsp_blocks_1071949_1_size,
    .dsp_blocks = ei_dsp_blocks_1071949_1,

    .learning_blocks_size = ei_learning_blocks_1071949_1_size,
    .learning_blocks = ei_learning_blocks_1071949_1,

    .postprocessing_blocks_size = ei_postprocessing_blocks_1071949_1_size,
    .postprocessing_blocks = ei_postprocessing_blocks_1071949_1,

    .output_tensors_size = 1,

    .inferencing_engine = EI_CLASSIFIER_TFLITE,

    .sensor = EI_CLASSIFIER_SENSOR_FUSION,
    .fusion_string = "dbfs_mean + dbfs_std + dbfs_range + f_peak_acoustic_hz_mean + f_peak_acoustic_hz_std + f_peak_acoustic_hz_range + low_rumble_ratio_mean + low_rumble_ratio_std + low_rumble_ratio_range + band_bass_ratio_mean + band_bass_ratio_std + band_bass_ratio_range + band_low_mid_ratio_mean + band_low_mid_ratio_std + band_low_mid_ratio_range + band_mid_ratio_mean + band_mid_ratio_std + band_mid_ratio_range + band_presence_ratio_mean + band_presence_ratio_std + band_presence_ratio_range + band_high_ratio_mean + band_high_ratio_std + band_high_ratio_range + band_bass_peak_hz_mean + band_bass_peak_hz_std + band_bass_peak_hz_range + band_low_mid_peak_hz_mean + band_low_mid_peak_hz_std + band_low_mid_peak_hz_range + band_mid_peak_hz_mean + band_mid_peak_hz_std + band_mid_peak_hz_range + band_presence_peak_hz_mean + band_presence_peak_hz_std + band_presence_peak_hz_range + band_high_peak_hz_mean + band_high_peak_hz_std + band_high_peak_hz_range + dominant_band_ratio_mean + dominant_band_ratio_std + dominant_band_ratio_range + dominant_band_peak_hz_mean + dominant_band_peak_hz_std + dominant_band_peak_hz_range + fft_low_ratio_mean + fft_low_ratio_std + fft_low_ratio_range + fft_mid_ratio_mean + fft_mid_ratio_std + fft_mid_ratio_range + fft_high_ratio_mean + fft_high_ratio_std + fft_high_ratio_range + fft_total_energy_mean + fft_total_energy_std + fft_total_energy_range",
    .slice_size = (1/4),
    .slices_per_model_window = 4,

    .has_anomaly = EI_ANOMALY_TYPE_UNKNOWN,
    .label_count = 3,
    .categories = ei_classifier_inferencing_categories_1071949_1,
    .results_type = EI_CLASSIFIER_TYPE_CLASSIFICATION,
    .freeform_outputs_size = freeform_outputs_1071949_1_size,
    .freeform_outputs = freeform_outputs_1071949_1
};

ei_impulse_handle_t impulse_handle_1071949_1 = ei_impulse_handle_t( &impulse_1071949_1 );

ei_impulse_handle_t& ei_default_impulse = impulse_handle_1071949_1;
constexpr auto& ei_classifier_inferencing_categories = ei_classifier_inferencing_categories_1071949_1;
const auto ei_dsp_blocks_size = ei_dsp_blocks_1071949_1_size;
ei_model_dsp_t *ei_dsp_blocks = ei_dsp_blocks_1071949_1;
#endif // _EI_CLASSIFIER_MODEL_VARIABLES_H_
